dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/list/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.list setup.py nosetests --ckan --with-pylons=ckanext/list/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.list --rednose

after_success: coveralls
